### ISSUE TITLE
bootJar fails to start

### ISSUE THREAD

**Issue by DuncanCasteleyn** [discord-java/opus-java#1]
When the opus-java dependency is added the opus-java-1.0.4.pom is added to the BOOT-INF/lib folder, this causes the application to fail to start and having to delete this file from the jar each time Gradle builds a bootJar.

```
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/opus-java-1.0.4.pom
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:108)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:86)
	at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:70)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/opus-java-1.0.4.pom'
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:254)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:239)
	at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
	... 4 more
Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 815 bytes
	at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.<init>(CentralDirectoryEndRecord.java:65)
	at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:52)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:121)
	at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:109)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:287)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:262)
	at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:250)
	... 6 more

Process finished with exit code 1
```

Is there a way to work around this issue?

**Comment by schnapster** [comment]
Exclude it in your `build.gradle`
Example:
```groovy
configurations {
    compile.exclude module: 'opus-java'
}
```

**Comment by DuncanCasteleyn** [comment]
> 
> 
> Exclude it in your `build.gradle`
> Example:
> 
> ```groovy
> configurations {
>     compile.exclude module: 'opus-java'
> }
> ```

I did something similar, but excluding this module removes this whole dependency so this includes the jar files that are working fine.

**Comment by MinnDevelopment** [comment]
This is an issue with spring and not this library.

**Comment by DuncanCasteleyn** [comment]
This issue is only present since the latest version, in IntliJ the .pom file also is listed as dependency together with the jar files. If I report this issue to Spring Boot repository there just going to direct me back here, this a problem with this library configuration not with Spring.

![afbeelding](https://user-images.githubusercontent.com/10881109/47298557-695c0e80-d618-11e8-9383-689d7a0d9aa1.png)

**Comment by DuncanCasteleyn** [comment]
I solved the issue myself, using `@pom` in the dependency causes this issue, so I simply excluded it and added it myself without the @pom. Since the readme of the project advices everyone to add @pom this is an issue created by this library. removing the @pom also removes the .pom file from the external libraries list, other dependencies presist.

```
    compile('net.dv8tion:JDA:3.8.1_439') {
        exclude group: 'club.minnced', module: 'opus-java'
    }
    compile ('club.minnced:opus-java:1.0.4')
```

**Comment by MinnDevelopment** [comment]
>Since the readme of the project advices everyone to add @pom this is an issue created by this library

Actually, spring-boot concluded this is a bug on their part and fixed it in a newer version. See spring-projects/spring-boot#16001 and gradle/gradle#8582

What I recommend in my README is the correct behavior as it is required to be compatible with maven.
